In [2]:
# for basic operation
import numpy as pd
import pandas as pd

# for Data Visualizations
import matplotlib.pyplot as plt
import seaborn as sns

# setting the Chart
plt.rcParams['figure.figsize'] = (16, 5)
plt.style.use('fivethirtyeight')

In [5]:
# lets read the dataset
data = pd.read_csv(r"C:\Users\Piyush GAJ\Downloads\Mall_Customers.csv")
print(data.shape)
print(data.columns)

(10, 5)
Index(['CustomerID', 'Gender', 'Age', 'Annual Income (k$)',
       'Spending Score (1-100)'],
      dtype='object')

Divide Age into Discrete Categories

In [6]:
print("Minimum Age :", data['Age'].min())
print("Maximum Age :", data['Age'].max())

Minimum Age : 19
Maximum Age : 64

In [7]:
# lets create a function to divide age into discrete categories
def age(x):
    if x <= 35:
        return "Younng"
    else:
        return "Old"

data['Age'] = data['Age'].apply(age)
data['Age'].value_counts()

Age
Younng    9
Old       1
Name: count, dtype: int64

Understanding the Impact of Spending score
on Different Age Groups

In [8]:
# lets use the groupby function to understand that
data[['Age', 'Spending Score (1-100)']].groupby(['Age']).agg(['min','mean','max']).style.background_gradient(cmap = 'copper')

Find out the Top 10 Target Customers

In [15]:
# To get the Target Customers we will use the Spending score and the Annual Income

data[['Annual Income (k$)','Spending Score (1-100)']].head()

   Annual Income (k$)  Spending Score (1-100)
0                  15                      39
1                  15                      81
2                  16                       6
3                  16                      77
4                  17                      40

In [19]:
# let's filter the Top Customers
data[['CustomerID','Annual Income (k$)','Spending Score (1-100)']][(data['Annual Income (k$)'] > 75)
        & (data['Spending Score (1-100)'] > 75)].sort_values(by = 'Spending Score (1-100)', ascending = False).head(10)

Empty DataFrame
Columns: [CustomerID, Annual Income (k$), Spending Score (1-100)]
Index: []